joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50  
move_group:
  controller_list:
  - name: excavator_effort_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - waist
      - shoulder
      - elbow
      - wrist

excavator_position_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - waist
    - shoulder
    - elbow
    - wrist

excavator_velocity_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - waist
    - shoulder
    - elbow
    - wrist
  gains:
    waist:    {p: 0.01,  d: 0, i: 0, i_clamp: 1}
    shoulder: {p: 0.01,  d: 0, i: 0, i_clamp: 1}
    elbow:    {p: 0.01,  d: 0, i: 0, i_clamp: 1}
    wrist:    {p: 0.01,  d: 0, i: 0, i_clamp: 1}

excavator_effort_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - waist
    - shoulder
    - elbow
    - wrist
  gains:
    waist:    {p: 100,  d: 0, i: 0, i_clamp: 1}
    shoulder: {p: 100,  d: 0, i: 0, i_clamp: 1}
    elbow:    {p: 100,  d: 0, i: 0, i_clamp: 1}
    wrist:    {p: 100,  d: 0, i: 0, i_clamp: 1}
  velocity_ff:
    waist:    1.0
    shoulder: 1.0
    elbow:    1.0
    wrist:    1.0
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.02
    waist:    {trajectory: 0.05, goal: 0.02}
    shoulder: {trajectory: 0.05, goal: 0.02}
    elbow:    {trajectory: 0.05, goal: 0.02}
    wrist:    {trajectory: 0.05, goal: 0.02}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25


  #  Unused Joint Controller Parameters  - 
  # constraints:
  #   waist:
  #     trajectory: 0.05
  #     goal: 0.05
  #   shoulder:
  #     trajectory: 0.05
  #     goal: 0.05
  #   elbow:
  #     trajectory: 0.05
  #     goal: 0.05
  #   wrist:
  #     trajectory: 0.05
  #     goal: 0.05
